//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDBExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FavoriteColor { get; set; }

        public string getSummary() {
            return String.Format("Employee Name:{0} Favorite Color:{1} Database ID Number:{2}");
        }
    }
}
